### PR TITLE
Runlocalscript

### PR DESCRIPTION
**Pull request by nils-ohlmeier**
A bash script which starts steeplechase with a local simplesignaling server and two local Negatus on a Linux system.

### CODE REVIEW

**Comment by sydvicious** [comment]
Don't like command-line arguments, eh? That's a matter of taste; I hate environment variables because they are a pain in things like Jenkins.

**Comment by nils-ohlmeier** [comment]
If there would be something like nice command line argument parsing for bash, e.g. --mozilla-central /foo/bar, I would use it.
I only know of $1, $2 etc and then all the arguments have to be exactly the right order, which sucks especially if you want to specify only a single argument.

**Comment by sydvicious** [comment]
I would use getopts.

**Comment by nils-ohlmeier** [comment]
On Mar 5, 2015, at 4:25 PM, Syd Polk <notifications@github.com> wrote:
> 
> I would use getopts.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/mozilla/steeplechase/pull/7#issuecomment-77482586>.
> 
Ok, I’ll add that.

**Comment by luser** [comment]
If I find myself having to do commandline handling I write a Python script, but that's just me. (And now you're partway to writing a mozharness script!)

**Comment by luser** [comment]
This looks fine and useful and I'm happy to merge it (although I think technically I will rebase and squash it) but there are some changes to the JS harness in there too, did you want those separated out?

**Comment by nils-ohlmeier** [comment]
As I wrote to Syd over IRC already: I'm not a big fan of process handling in Python. Although bash is probably just simpler in that regard, not more sophisticated :-)
I just named the script Linux as it only support Linux right now. I basically failed to figure out which build directory I would have to copy to get it working from within Negatus. But I thought one platform is better then nothing. And we could still rename/move it if we add support for Mac.
Yes the JS harness change is on purpose in here as I stumbled upon that while I was working on this script. If you prefer I can submit it separately.

I'll add the command line arguments and squash everything and then update or re-submit.

**Comment by nils-ohlmeier** [comment]
Added command line argument support and squashed into one commit.

Ted are you okay "hiding" this one change in the harness, or should I take it out?

**Comment by luser** [comment]
Fine with me, just wasn't sure if it was intentional.

**Pull request merged**
